import {
  AlertTriangle,
  Camera,
  CameraOff,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  File,
  FileUp,
  Globe,
  LoaderCircle,
  Maximize,
  Minimize,
  Moon,
  OctagonAlert,
  QrCode,
  RotateCw,
  ScanLine,
  Settings,
  ShieldCheck,
  Sun,
  Upload,
  X,
  Zap,
  ZapOff,
  type LucideIcon,
} from 'lucide-react'

// The 28-icon inventory this app actually uses — docs/DESIGN_SYSTEM.md §4.8.
export const ICONS = {
  'qr-code': QrCode,
  'scan-line': ScanLine,
  upload: Upload,
  'file-up': FileUp,
  file: File,
  x: X,
  copy: Copy,
  check: Check,
  'check-circle': CheckCircle,
  'shield-check': ShieldCheck,
  'alert-triangle': AlertTriangle,
  'octagon-alert': OctagonAlert,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  globe: Globe,
  zap: Zap,
  'zap-off': ZapOff,
  camera: Camera,
  'camera-off': CameraOff,
  'rotate-cw': RotateCw,
  maximize: Maximize,
  minimize: Minimize,
  'loader-circle': LoaderCircle,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
